In [2]:
import pandas as pd
import numpy as np

In [4]:
file_path = "../Data/df__methaq.csv"
data = pd.read_csv(file_path)

data.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_4552\1335290432.py:2: DtypeWarning: Columns (1,7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,price
0,JTFHX02P7F0094323,2015,TOYOTA,HIACE,DX,Mini Bus High Roof,GCC,4.0,white,Japan,1837.0,15.0,48400.0
1,JTFHX02P7F0094323,2015,TOYOTA,HIACE,DX,Mini Bus High Roof,GCC,4.0,white,Japan,1837.0,15.0,48400.0
2,JTFHXDGP7F0094373,2015,TOYOTA,HILUX,DL,Pick Up Double Cab,GCC,4.0,white,Japan,1837.0,5.0,37800.0
3,JN1ASNYC3PU200564,2024,INFINITI,QX50,LUXE STYLE,SUV,GCC,4.0,grey,Mexico,1898.0,5.0,142000.0
4,WBA11AP04RCR41747,2024,BMW,420I,M SPORT PREMIUM,COUPE,GCC,4.0,black,Germany,1525.0,4.0,156500.0

In [6]:
data = data.loc[data['make'].map(data['make'].value_counts()).sort_values(ascending=False).index]
data

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,price
1674107,NaN,2024.0,TOYOTA,HILUX,SGLX,Pick Up Double Cab,GCC,4.0,NaN,Japan,3000.0,5.0,86400.0
0,JTFHX02P7F0094323,2015,TOYOTA,HIACE,DX,Mini Bus High Roof,GCC,4.0,white,Japan,1837.0,15.0,48400.0
1,JTFHX02P7F0094323,2015,TOYOTA,HIACE,DX,Mini Bus High Roof,GCC,4.0,white,Japan,1837.0,15.0,48400.0
2,JTFHXDGP7F0094373,2015,TOYOTA,HILUX,DL,Pick Up Double Cab,GCC,4.0,white,Japan,1837.0,5.0,37800.0
1674082,JTDBR23E743091273,2004.0,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,maroon,Japan,1025.0,5.0,3500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466591,KMHLN4TB8NU216T80,NaN,NaN,NaN,NaN,Sedan,GCC,4.0,NaN,NaN,1.0,4.0,100000.0
1466602,KMHLN4TB8NU216T80,NaN,NaN,NaN,NaN,Sedan,GCC,4.0,NaN,NaN,1.0,4.0,100000.0
1466623,KMHLN4TB8NU216T80,NaN,NaN,NaN,NaN,Sedan,GCC,4.0,NaN,NaN,1.0,4.0,100000.0
1518848,TZ220XYF3G5001767,NaN,NaN,NaN,NaN,Sedan,GCC,NaN,NaN,NaN,1.0,4.0,100000.0
1603160,JTJPD7CX954001287,NaN,NaN,NaN,NaN,Sedan,GCC,NaN,NaN,NaN,1.0,4.0,100000.0

In [13]:
import pandas as pd

# Load dataset
# Create lookup dataframe
lookup_data = (
    data[
        ['chassisNumber','make', 'model', 'year', 'trim', 'price']
    ]
    .drop_duplicates(
        subset=['make', 'model', 'year', 'trim'],
        keep='first'
    )
    .reset_index(drop=True)
)

# View lookup table
print(lookup_data.head())

print("\nLookup Table Shape:")
print(lookup_data.shape)

# Create dictionary for fast valuation lookup
lookup_dict = lookup_data.set_index(
    ['make', 'model', 'year', 'trim']
)['price'].to_dict()

# Example lookup
make = "TOYOTA"
model = "CAMRY"
year = 2024
trim = "XLE"

price = lookup_dict.get(
    (make, model, year, trim)
)

print(f"\nPrice: {price}")

       chassisNumber    make    model    year  trim    price
0                NaN  TOYOTA    HILUX  2024.0  SGLX  86400.0
1  JTFHX02P7F0094323  TOYOTA    HIACE    2015    DX  48400.0
2  JTFHXDGP7F0094373  TOYOTA    HILUX    2015    DL  37800.0
3  JTDBR23E743091273  TOYOTA  COROLLA  2004.0   XLI   3500.0
4                NaN  TOYOTA    CAMRY  2025.0   GLE  99800.0

Lookup Table Shape:
(69477, 6)

Price: None

In [19]:
lookup_data = lookup_data.loc[lookup_data['model'].map(lookup_data['model'].value_counts()).sort_values(ascending=False).index]
lookup_data

           chassisNumber        make   model  year         trim    price
11098        WGY60317809      NISSAN  PATROL  1990     STANDARD      0.0
9444   JNBBT0BV05W103640      NISSAN  PATROL  2005     STANDARD      0.0
9488   JN10UGY60Z0097117      NISSAN  PATROL  1996          STD      0.0
11006  JN1TBSY61Z0400355      NISSAN  PATROL  1998           EX      0.0
6953   JN8BY2NY6L9312758      NISSAN  PATROL  2020  SE TITANIUM  92900.0
...                  ...         ...     ...   ...          ...      ...
18513  ME4KC311GJ8346376       HONDA     NaN  2018          NaN      0.0
18670  ME4KC40A4TA005771       HONDA     NaN  2026          NaN      0.0
18812  1HFSC47FX6A504064       HONDA     NaN  2006          NaN      0.0
41128  WV1DAZSV9GH003041  VOLKSWAGEN     NaN  2016          NaN      0.0
69467  LRW3E7ES9RC964797         NaN     NaN   NaN          NaN      0.0

[69477 rows x 6 columns]