In [1]:
import pandas as pd

df = pd.read_csv("data_methaq(2.0).csv")

In [2]:
df.shape

(1009604, 12)

In [3]:
df.dtypes

chassisNumber         str
year              float64
make                  str
model                 str
trim                  str
bodyType              str
regionalSpec          str
cylinders         float64
color                 str
origin                str
weightInKg        float64
noOfPassengers    float64
dtype: object

In [4]:
df.isnull().sum()

chassisNumber          0
year                  11
make                  11
model                 13
trim               19411
bodyType               1
regionalSpec         283
cylinders          18687
color              63616
origin             85061
weightInKg        102248
noOfPassengers         7
dtype: int64

In [5]:
df[['make','model','trim','bodyType','regionalSpec']].nunique()

make             466
model           6403
trim            3256
bodyType         128
regionalSpec       2
dtype: int64

In [6]:


print(*df['bodyType'].unique(), sep='\n')

SEDAN
Mini Bus High Roof
Pick Up Double Cab
SUV
HATCHBACK
Pick Up Single Cab
Panel Van
BUS
MPV
Estate
Pick Up
VAN
Mini Bus
COUPE
Van
SUV- CROSSOVER
PICKUP
SALOON
Sedan
Station
Saloon
Panel Van High Roof
Pickup
Hatchback
MINI BUS
PICK UP SINGLE CAB
Half Panel Van
PICK UP DOUBLE CAB
CONVERTIBLE
PANEL VAN
Coupe
CARGO VAN
MINIVAN
Mini Bus Semi High Roof
Pickup Double Cabin
Bus
PICK UP
Light Vehicle
CARAVAN
TANKER
PICKUP TRUCK
Car
Motorcycle
Pickup Single Cabin
Minivan
Pickup Double Cab
Truck
Pick Up Double Cabin
COUPE/CABRIOLET
Forklift
Ambulance
Regular Cab
Window Van
MINI BUS HIGH ROOF
MOTORCYCLE
STATION
Wagon
Station Wagon
PICK-UP
PanelVan Wide Body High Roof
LIGHT VEHICLE
Refrigerator
Pick-Up
TRUCK
Pick Up Double C
Van Cargo
Pick-Up with crane
Truck with Crane
Water Tank
Sports Car
Station Light
Sedan Light Vehicle
Mini Bus LWB Wide Body HR
Diesel Tanker
sedan
coupe
SINGLE CABIN LONG CHASSIS
SINGLE CABIN LONG CARGO
Pick Up LWB
SINGLE CABIN STD CHASSIS
PICK UP DOUBLE CAB LONG BOX
PICK-UP WITH BOX
COACH
Dump Truck
Mitsubishi
REGULAR CAB
HEAVY EQUIPMENT
Pickup Refrigerator
Heavy Truck
CROSSOVER
Van Passenger
PICK UP DOUBLE CABIN
Mini Van
Mobile Workshop
WAGON
Pick Up Cargo
VAN PASSENGER
SUV COUPE
Mini Bus LWB
SPORTS CAR
MINI VAN
Convertible
Caravan
nan
PICK UP EXT CAB
SUV- COMPACT
Targa
VAN CARGO
SUV CONVERTIBLE
SWB VAN
LWB VAN
Hard Top
Pick-Up with Box
PICK UP CARGO
HARD TOP
JEEP WRANGLER
Crane
Pick Up Double
SPORTBACK
VAN 4.5 TON
LONG VAN
MINI
Truck with Box
Locomotive
FORK LIFT
Pickup with Box
Cargo Van
Excavator
Trailer

In [7]:
pd.set_option("display.max_rows", None)

In [8]:
df.shape

(1009604, 12)

In [9]:
long_chassis_df = df[df['chassisNumber'].astype(str).str.replace(r'\s+', '', regex=True).str.len() > 17]

In [10]:
df = df.drop(index=long_chassis_df.index)

In [11]:
df.shape

(1009418, 12)

In [12]:
df = df[df['chassisNumber'].astype(str).str.replace(r'\s+', '', regex=True).str.len() >= 17]

In [13]:
df[df['bodyType'] == 'Light Vehicle']

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
41955,JTNBZ4HK7N3023062,2012.0,TOYOTA,CAMRY,NaN,Light Vehicle,NaN,NaN,white pearl,JAPAN,1630.0,5.0
73247,JTFLU733196053119,2009.0,TOYOTA,LAND CRUISER,NaN,Light Vehicle,NaN,NaN,silver,Japan,1000.0,3.0
122415,JT152EEA100287105,1996.0,TOYOTA,COROLLA 1.6/SEDAN,NaN,Light Vehicle,NaN,NaN,red,Japan,1100.0,4.0
139398,WZIDB4A03LW033661,2020.0,TOYOTA,SUPRA COUPE,NaN,Light Vehicle,NaN,NaN,gray and black,Austria,1570.0,2.0
195455,JTNYM3AP2P8002523,2023.0,TOYOTA,VAN,NaN,Light Vehicle,NaN,NaN,black,JAPAN,2440.0,6.0
201367,JTJHK31U102001109,2022.0,TOYOTA,LAND CRUISER,NaN,Light Vehicle,NaN,NaN,white,JAPAN,2000.0,7.0
215938,JTMHY05J6M4100065,2021.0,TOYOTA,LAND CRUISER,NaN,Light Vehicle,NaN,NaN,white pearl,Japan,2590.0,8.0
227205,JTDBW9232A1191208,2010.0,TOYOTA,YARIS,NaN,Light Vehicle,NaN,NaN,gray and black,JAPAN,900.0,5.0
248512,JN8AY2NY4F9118505,2015.0,NISSAN,PATROL,NaN,Light Vehicle,NaN,NaN,black,Japan,2150.0,8.0
277163,JN6FE54852X401040,2002.0,NISSAN,URVAN/COACH,NaN,Light Vehicle,NaN,NaN,white,Japan,2000.0,12.0
383064,WBAKRO104HOW31291,2008.0,NISSAN,PATROL SUPER SA,NaN,Light Vehicle,NaN,NaN,white,JAPAN,1800.0,7.0
385627,3N8AP6BA8SL385567,2025.0,NISSAN,KICKS,NaN,Light Vehicle,NaN,NaN,black,MEXICO,1350.0,5.0
425423,MNTBDOES3G6630716,2016.0,NISSAN,NAVARA,NaN,Light Vehicle,NaN,NaN,white,Thailand,2200.0,5.0
537758,MMBJNK340GH005409,2016.0,MITSUBISHI,200,NaN,Light Vehicle,NaN,NaN,white,THAILAND,1600.0,1.0
548308,JE3AB36AXHU715639,2017.0,MITSUBISHI,LANCER,NaN,Light Vehicle,NaN,NaN,gray and black,Japan,1310.0,5.0
552025,JA3AW86VX8U043266,2008.0,MITSUBISHI,LANCER EVOLUTION,NaN,Light Vehicle,NaN,NaN,maroon,Japan,1100.0,5.0
614859,KMJWA37JBAU169508,2010.0,HYUNDAI,STARKS,NaN,Light Vehicle,NaN,NaN,silver,South Korea,1600.0,10.0
700055,WDD2211561A008241,2006.0,MERCEDES BENZ,S350,NaN,Light Vehicle,NaN,NaN,gray and black,Germany,1955.0,5.0
740454,6G1EK52827L875838,2007.0,CHEVROLET,LUMINA,NaN,Light Vehicle,NaN,NaN,white,Australia,1720.0,5.0
794990,WBA3B5G67ENS10088,2014.0,BMW,328,NaN,Light Vehicle,NaN,NaN,black,Germany,NaN,NaN
799181,WBA23EHOXPCM38824,2023.0,BMW,BMW 740,NaN,Light Vehicle,NaN,NaN,green and white,United States,1800.0,5.0
799586,WBS41AZ040CM88996,2023.0,BMW,M4,NaN,Light Vehicle,NaN,NaN,black,Germany,2000.0,2.0
800618,WBA71AGOXPWX92881,2023.0,BMW,5201,NaN,Light Vehicle,NaN,NaN,white,Austria,1615.0,5.0
801958,WBABS51080EH36590,2003.0,BMW,330 CI COUPE,NaN,Light Vehicle,NaN,NaN,white,Germany,1600.0,5.0
861486,LVUDB2182PF022834,2023.0,JETOUR,X70,NaN,Light Vehicle,NaN,NaN,white,China,2100.0,7.0
882495,JNKBY1AP8HM340020,2017.0,INFINITI,Q70/SEDAN,NaN,Light Vehicle,NaN,NaN,gray and black,JAPAN,1600.0,5.0
906164,LCOFD1C40S5384246,2025.0,BYD,LEOPARD 5,NaN,Light Vehicle,NaN,NaN,black,China,2800.0,5.0
907572,LCOFD1C42S5245557,2025.0,BYD,LEOPARD 5,NaN,Light Vehicle,NaN,NaN,black,China,1600.0,5.0
909789,LGXCE4CB6S0586521,2025.0,BYD,SONG PLUS,NaN,Light Vehicle,NaN,NaN,gray and black,China,1400.0,5.0
910361,LCOFD1C46S5284409,2025.0,BYD,LEOPARD 5,NaN,Light Vehicle,NaN,NaN,black,CHINA,2500.0,5.0
925131,WAUAYABX3BB069743,2011.0,AUDI,A1,NaN,Light Vehicle,NaN,NaN,brown,Belgium,1300.0,4.0
954376,L6T716228HN407654,2017.0,GEELY,EX7 SPORT,NaN,Light Vehicle,NaN,NaN,white,CHINA,1200.0,4.0
990703,HH415QPA24J601986,2025.0,VICTORY,V2,NaN,Light Vehicle,NaN,NaN,white,China,1700.0,5.0
1004305,JHHZCNIH2KK010517,2019.0,HINO,300 PICK UP CARGO,NaN,Light Vehicle,NaN,NaN,white,Japan,2400.0,4.0

In [17]:
summary = (
    df.groupby(['make', 'model', 'trim', 'noOfPassengers', 'cylinders', 'weightInKg'])
      .agg(
          unique_body_types=('bodyType', 'nunique'),
          body_types=('bodyType', lambda x: list(sorted(set(x))))
      )
      .reset_index()
)

# Filter for conflicts (Make sure there is no comma at the end of this line!)
summary = summary[summary['unique_body_types'] > 1]

# Display the DataFrame
summary

                 make                   model                         trim  \
8              ABARTH                     595                 COMPETIZIONE
13             ABARTH                     595                 COMPETIZIONE
41             ABARTH                     695                      TURISMO
219     ASHOK LEYLAND           ASHOK LEYLAND                          STD
270     ASHOK LEYLAND                 PARTNER                          STD
342      ASTON MARTIN                 VANTAGE                     ROADSTER
425              AUDI                      A3                      35 TFSI
442              AUDI                      A3                      35 TFSI
666              AUDI                      A4                       S-Line
739              AUDI                      A4                       S-Line
802              AUDI                      A5                      35 TFSI
810              AUDI                      A5                      40 TFSI
815              AUDI                      A5                      40 TFSI
816              AUDI                      A5                      40 TFSI
821              AUDI                      A5                      40 TFSI
843              AUDI                      A5               40 TFSI S-LINE
850              AUDI                      A5               40 TFSI S-LINE
875              AUDI                      A5               40 TFSI S-LINE
884              AUDI                      A5               45 TFSI S-LINE
898              AUDI                      A5               45 TFSI S-LINE
908              AUDI                      A5                       S-Line
914              AUDI                      A5                       S-Line
915              AUDI                      A5                       S-Line
923              AUDI                      A5                       S-Line
924              AUDI                      A5                       S-Line
930              AUDI                      A5                       S-Line
933              AUDI                      A5                       S-Line
963              AUDI                      A5                          STD
965              AUDI                      A5                          STD
969              AUDI                      A5                          STD
972              AUDI                      A5                          STD
973              AUDI                      A5                          STD
979              AUDI                      A5                          STD
980              AUDI                      A5                          STD
996              AUDI                      A5                          STD
1631             AUDI                      Q2                      35 TFSI
1824             AUDI                      Q5                      40 TFSI
2396             AUDI                      Q8                      55 TFSI
2499             AUDI                     RS3                          STD
2502             AUDI                     RS3                          STD
2503             AUDI                     RS3                          STD
2507             AUDI                     RS3                          STD
2513             AUDI                     RS3                          STD
2516             AUDI                     RS3                          STD
2524             AUDI                     RS3                          STD
2594             AUDI                      S3                          STD
2598             AUDI                      S3                          STD
2600             AUDI                      S3                          STD
2602             AUDI                      S3                          STD
2604             AUDI                      S3                          STD
2611             AUDI                      S3                          STD
2617             AUDI                      S3                          STD
2618             AUDI                      S3                          STD
2628             AUDI                      S3                          STD
2634             AUDI                      S3                          STD
2641             AUDI                      S3                          STD
2665             AUDI                      S5                          STD
2668             AUDI                      S5                          STD
2829             AUDI                      TT               45 TFSI S-LINE
2873             AUDI                      TT                          STD
2961            AVATR                      12                STD (NON GCC)
2962            AVATR                      12                STD (NON GCC)
2963            AVATR                      12                STD (NON GCC)
2964            AVATR                      12                STD (NON GCC)
2967            AVATR                      12                STD (NON GCC)
2969            AVATR                      12                STD (NON GCC)
3433          BENTLEY             CONTINENTAL                           GT
3499          BENTLEY             CONTINENTAL                GT SUPERSPORT
3500          BENTLEY             CONTINENTAL                GT SUPERSPORT
3501          BENTLEY             CONTINENTAL                GT SUPERSPORT
3642          BENTLEY             FLYING SPUR                          W12
3958              BMW                    220I                          STD
4284              BMW                    320I                          STD
4288              BMW                    320I                          STD
4292              BMW                    320I                          STD
4310              BMW                    320I                          STD
4345              BMW                    320I                          STD
4353              BMW                    320I                          STD
4378              BMW                    320i                          STD
4450              BMW                    325I                          STD
4486              BMW                    325I                          STD
4492              BMW                    325i                          STD
4567              BMW                    328I                          STD
4706              BMW                    330I                          STD
4775              BMW                    335I                          STD
4829              BMW                    420I                      M SPORT
4839              BMW                    420I                      M SPORT
4847              BMW                    420I                      M SPORT
4849              BMW                    420I                      M SPORT
4851              BMW                    420I                      M SPORT
4901              BMW                    420I                  SPORTS LINE
4903              BMW                    420I                  SPORTS LINE
4907              BMW                    420I                  SPORTS LINE
4921              BMW                    420I                  SPORTS LINE
5009              BMW                    428I                   SPORT LINE
5011              BMW                    428I                  SPORTS LINE
5039              BMW                    430I                      M SPORT
5042              BMW                    430I                      M SPORT
5043              BMW                    430I                      M SPORT
5046              BMW                    430I                      M SPORT
5050              BMW                    430I                      M SPORT
5052              BMW                    430I                      M SPORT
5058              BMW                    430I                      M SPORT
5065              BMW                    430I                      M SPORT
5067              BMW                    430I                      M SPORT
5070              BMW                    430I                      M SPORT
5072              BMW                    430I                      M SPORT
5075              BMW                    430I                      M SPORT
5078              BMW                    430I                      M SPORT
5079              BMW                    430I                      M SPORT
5080              BMW                    430I                      M SPORT
5084              BMW                    430I                      M SPORT
5085              BMW                    430I                      M SPORT
5121              BMW                    435I                      M Sport
5122              BMW                    435I                      M Sport
5123              BMW                    435I                      M Sport
5125              BMW                    435I                      M Sport
5133              BMW                    435I                      M Sport
5137              BMW                    435I                      M Sport
5164              BMW                    440I                      M SPORT
5167              BMW                    440I                      M SPORT
5557              BMW                    525I                          STD
5638              BMW                    528I                       LUXURY
6071              BMW                    640I                          STD
6150              BMW                    650I                      M SPORT
6163              BMW                    650I                     M SPORTS
6169              BMW                    650I                          STD
6173              BMW                    650I                          STD
6188              BMW                    650I                          STD
6732              BMW                   750LI                    EXCLUSIVE
6833              BMW                   750LI                XDRIVE LUXURY
6952              BMW                    840I                      M SPORT
6982              BMW                  ALPINA                           B6
7052              BMW                 BMW 530                          STD
7102              BMW           I4 GRAN COUPE                    EDRIVE 35
7304              BMW                      M3                          STD
7366              BMW                      M4                  COMPETITION
7386              BMW                      M4                           CS
7397              BMW                      M4                M COMPETITION
7412              BMW                      M4                          STD
7427              BMW                   M440I                       XDRIVE
7440              BMW                   M440I                       XDRIVE
7441              BMW                   M440I                       XDRIVE
7443              BMW                   M440I                       XDRIVE
7491              BMW                      M5                          STD
7526              BMW                      M6                          STD
7531              BMW                      M8                M COMPETITION
7537              BMW                      M8                M COMPETITION
7550              BMW                   M850I                       xDrive
7551              BMW                   M850I                       xDrive
7552              BMW                   M850I                       xDrive
7554              BMW                   M850I                       xDrive
7557              BMW                   M850I                       xDrive
7562              BMW                   M850I                       xDrive
7564              BMW                   M850I                       xDrive
7565              BMW                   M850I                       xDrive
7567              BMW                   M850I                       xDrive
7649              BMW                      X1           XDRIVE 20i M SPORT
7798              BMW                      X3                           SI
7956              BMW                      X4           XDRIVE 28I M SPORT
8820              BMW                      X6                35i EXECUTIVE
8943              BMW                      X6                        M 50i
8994              BMW                      X6                   XDRIVE 50i
9002              BMW                      X6                   XDRIVE 50i
9166              BMW                      X6          XDRIVE50i EXCLUSIVE
9173              BMW                    X6 M                          STD
9176              BMW                    X6 M                          STD
9349              BMW                      Z4                        25 Si
9366              BMW                      Z4                          STD
9384              BMW                      Z4                   sDrive 20i
9389              BMW                      Z4           sDrive 20i M SPORT
9573              BYD                     HAN                      PREMIUM
9587              BYD                     HAN                      PREMIUM
9695              BYD               LEOPARD 5                STD (NON GCC)
9699              BYD               LEOPARD 5                STD (NON GCC)
9700              BYD               LEOPARD 5                STD (NON GCC)
9783              BYD               LEOPARD 7               STD  (NON GCC)
9888              BYD               LEOPARD 8                 DELUX (NGCC)
10058             BYD                QIN PLUS                      PREMIUM
10092             BYD                SEA LION                          STD
10227             BYD                  SONG L                STD (NON GCC)
10266             BYD               SONG PLUS                          FWD
10277             BYD               SONG PLUS                          FWD
10459        CADILLAC                     ATS                          STD
10467        CADILLAC                     ATS                          STD
10468        CADILLAC                     ATS                          STD
10470        CADILLAC                     ATS                          STD
10472        CADILLAC                     ATS                          STD
10474        CADILLAC                     ATS                          STD
10476        CADILLAC                     ATS                          STD
10481        CADILLAC                     ATS                          STD
10484        CADILLAC                     ATS                          STD
10523        CADILLAC                     CT4                       LUXURY
10624        CADILLAC                     CT6                     PLATINUM
10697        CADILLAC                     CTS                       LUXURY
10743        CADILLAC                     CTS                          STD
10749        CADILLAC                     CTS                          STD
10750        CADILLAC                     CTS                          STD
10785        CADILLAC                 DEVILLE                          STD
10949        CADILLAC                ESCALADE                     PLATINUM
11255        CADILLAC                ESCALADE                          STD
11259        CADILLAC                ESCALADE                          STD
11358        CADILLAC               FLAT WOOD                          STD
11703         CHANGAN                  ALSVIN                      ADVANCE
11786         CHANGAN               CS35 PLUS                      LIMITED
12312           CHERY                   TIGGO                          STD
12354           CHERY                 TIGGO 7                       LUXURY
12532       CHEVROLET                   ASTRO                          STD
12548       CHEVROLET                   ASTRO                          STD
12556       CHEVROLET                   ASTRO                          STD
12592       CHEVROLET               AVALANCHE                      LT  Z71
12698       CHEVROLET                    AVEO                         BASE
12712       CHEVROLET                    AVEO                           LS
12718       CHEVROLET                    AVEO                           LS
12722       CHEVROLET                    AVEO                           LS
12725       CHEVROLET                    AVEO                           LS
12732       CHEVROLET                    AVEO                           LS
12740       CHEVROLET                    AVEO                           LS
12742       CHEVROLET                    AVEO                           LS
12749       CHEVROLET                    AVEO                           LS
12757       CHEVROLET                    AVEO                           LS
12761       CHEVROLET                    AVEO                           LS
12762       CHEVROLET                    AVEO                           LS
12765       CHEVROLET                    AVEO                           LS
12766       CHEVROLET                    AVEO                           LS
12770       CHEVROLET                    AVEO                           LS
12772       CHEVROLET                    AVEO                           LS
12776       CHEVROLET                    AVEO                           LT
12778       CHEVROLET                    AVEO                           LT
12949       CHEVROLET                  CAMARO                           LT
12950       CHEVROLET                  CAMARO                           LT
12952       CHEVROLET                  CAMARO                           LT
12955       CHEVROLET                  CAMARO                           LT
12960       CHEVROLET                  CAMARO                           LT
12963       CHEVROLET                  CAMARO                           LT
12969       CHEVROLET                  CAMARO                           LT
12983       CHEVROLET                  CAMARO                           LT
12987       CHEVROLET                  CAMARO                           LT
12989       CHEVROLET                  CAMARO                           LT
12993       CHEVROLET                  CAMARO                           LT
12994       CHEVROLET                  CAMARO                           LT
12995       CHEVROLET                  CAMARO                           LT
13008       CHEVROLET                  CAMARO                           LT
13016       CHEVROLET                  CAMARO                           LT
13023       CHEVROLET                  CAMARO                           LT
13025       CHEVROLET                  CAMARO                           LT
13072       CHEVROLET                  CAMARO                          LT2
13082       CHEVROLET                  CAMARO                          LT2
13167       CHEVROLET                  CAMARO                           SS
13173       CHEVROLET                  CAMARO                           SS
13177       CHEVROLET                  CAMARO                           SS
13178       CHEVROLET                  CAMARO                           SS
13181       CHEVROLET                  CAMARO                           SS
13183       CHEVROLET                  CAMARO                           SS
13192       CHEVROLET                  CAMARO                           SS
13193       CHEVROLET                  CAMARO                           SS
13194       CHEVROLET                  CAMARO                           SS
13200       CHEVROLET                  CAMARO                           SS
13206       CHEVROLET                  CAMARO                           SS
13214       CHEVROLET                  CAMARO                           SS
13219       CHEVROLET                  CAMARO                           SS
13230       CHEVROLET                  CAMARO                           SS
13231       CHEVROLET                  CAMARO                           SS
13232       CHEVROLET                  CAMARO                           SS
13235       CHEVROLET                  CAMARO                           SS

In [23]:
sorted(df['year'].unique())

[np.float64(1946.0),
 np.float64(1948.0),
 np.float64(1951.0),
 np.float64(1962.0),
 np.float64(1965.0),
 np.float64(1966.0),
 np.float64(1971.0),
 np.float64(1972.0),
 np.float64(1974.0),
 np.float64(1975.0),
 np.float64(1977.0),
 np.float64(1978.0),
 np.float64(1979.0),
 np.float64(1980.0),
 np.float64(1981.0),
 np.float64(1982.0),
 np.float64(1983.0),
 np.float64(1984.0),
 np.float64(1985.0),
 np.float64(1986.0),
 np.float64(1987.0),
 np.float64(1988.0),
 np.float64(1989.0),
 np.float64(1990.0),
 np.float64(1991.0),
 np.float64(1992.0),
 np.float64(1993.0),
 np.float64(1994.0),
 np.float64(1995.0),
 np.float64(1996.0),
 np.float64(1997.0),
 np.float64(1998.0),
 np.float64(1999.0),
 np.float64(2000.0),
 np.float64(2001.0),
 np.float64(2002.0),
 np.float64(2003.0),
 np.float64(2004.0),
 np.float64(2005.0),
 np.float64(2006.0),
 np.float64(2007.0),
 np.float64(2008.0),
 np.float64(2009.0),
 np.float64(2010.0),
 np.float64(2011.0),
 np.float64(2012.0),
 np.float64(2013.0),
 np.float64(2014.0),
 np.float64(2015.0),
 np.float64(2016.0),
 np.float64(2017.0),
 np.float64(2018.0),
 np.float64(2019.0),
 np.float64(2020.0),
 np.float64(2021.0),
 np.float64(2022.0),
 np.float64(2023.0),
 np.float64(2024.0),
 np.float64(2025.0),
 np.float64(2026.0),
 np.float64(nan),
 np.float64(2027.0),
 np.float64(2028.0)]

In [44]:
df.drop(index=df[df['year'] == 1946].index, inplace=True)

In [45]:
df[df['year'] == 1948]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
726776,2RKK4021555555555,1948.0,CHEVROLET,S 10,std,Pickup,GCC,6.0,red,AMERICA,1600.0,3.0

In [28]:
df['make'].value_counts().sort_index()

make
A                          1
ABARTH                   273
ACURA                     10
ADMIRAL                    1
AEOLUS                    58
AFTEK                      6
AIQAR                      1
AITO                      27
AL DAMANI                 18
ALFA ROMEO               253
AM                         1
APACHE                     1
APRILIA                   54
APULUO                     1
ARI                        1
ASHOK                      1
ASHOK LEYLAND             88
ASTON MARTIN             125
AUDI                    5993
AVATR                    204
AVENGER                    2
AYED                       9
AYED AYED                  1
AYED BIKE                  1
BAIC                     739
BAJA                       1
BAJAJ                   2229
BAOJUN                     1
BAOJUN YEP                 1
BAW                       24
BENDA                      3
BENELLI                   11
BENTLEY                 1115
BESTUNE                  478
BETA                       1
BIMOTA                     1
BIUE BAIRD                 1
BMW                    14902
BMWB                       1
BORGWARD                  23
BRILLIANCE                16
BUELL                      1
BUGATTI                   34
BUICK                      4
BYD                     5400
BYD - DENZA               82
BYD - YANGWANG            34
CADILLAC                3214
CAN                        2
CAN -AM                    1
CAN AM                     2
CAN AM SPYDER              1
CAN-AM                     6
CATERHAM                   2
CATERPILLAR                1
CF MOTO                    1
CF MOTO 700 CL X           1
CFMOTO                    44
CH                         1
CHAMP                      1
CHANGAN                 3851
CHANGHUA                   5
CHANGHUA - MAX180          1
CHANGUA                    1
CHERVOLET                 23
CHERY                    653
CHERY - ICAR             132
CHEVROLET              28094
CHRYSLER                 895
CITROEN                  124
CMC                       91
DAEWOO                     5
DAEWOO 106 BF              1
DAF                        1
DAIHATSU                1402
DATSUN                     5
DEEPAL                   112
DELOREAN                   1
DELTA                      1
DEXER                      1
DFSK                     195
DODGE                   6338
DONGFENG                  47
DONGFENG EΠ                6
DONGFENG-AEOLUS           43
DONGFENG-XIAOKA            3
DORCEN                     6
DUCATI                    60
ECOWAY                     2
EICHER                     4
ELECTRIC MOTION            1
EMPALA                     3
EQUATION                   1
ESCHER                     2
EXEED                    497
FANTIC                     1
FARIZON                    1
FAW                        6
FERRARI                  412
FIAT                     417
FLONY                      1
FOLONY                     6
FORCE                      2
FORD                   26183
FORTHING                 116
FOTON                     67
G10                        1
GAC                     1519
GAS GAS                    2
GEELY                   2524
GENESIS                 1204
GMC                    14470
GRAND TIGER                2
GREAT WALL               699
GUNAU                      2
GWM - WEY                  1
HAOJUE                    14
HAR                        1
HARLEY                     6
HARLEY DAVIDSON            4
HARLEY-DAVIDSON          392
HART FORD                  1
HAVAL                   1239
HERO                    1059
HH                         1
HIG                        1
HIGER                      1
HINO                     147
HIPHI                      2
HO                         1
HONDA                  52232
HONGQI                   535
HS                         1
HUAIHAI                    7
HUMMER                   432
HUSQVARNA                  5
HYCAN                      2
HYOSUNG                    2
HYUNDAI                44843
HYUNDAI2120117999          1
INDIAN                    49
INDIAN  MOTORCYCLE         1
INEOS                     83
INFINITI                9188
ISUZU                   1770
ITALJET                    1
IVECO                     34
JAC                     1729
JAECOO                    32
JAGUAR                  1208
JCB                        1
JEEP                    9538
JETOUR                  8259
JIDU                      15
JINBEI                     1
JIYUE                      1
JMC                       26
JOYLONG                    1
KAIYI                    107
KAMA                       1
KAN M                      1
KAOE K1                    1
KAWASAKI                 224
KAWAZAKI                   1
KIA                    34871
KIA41964                   1
KIMMCO                     1
KING LONG                 19
KOASKO                     1
KOASKO 0                   1
KOENIGSEGG                 1
KOVE                       1
KTM                       62
KYMCO                      6
LADA                      15
LAMBORGHINI              552
LANCIA                     1
LAND ROVER             15244
LEADING                    1
LEADING IDEAL             37
LEAPMOTOR                  4
LEAPMOTORS                11
LEOPARD                    1
LEXUS                  65166
LI                        31
LI AUTO                   10
LIEBHERR                   1
LIFAN                     16
LINCOLN                 2277
LIP MOTOR                  1
LIVEWIRE                   3
LIXIANG                    2
LONSIN                     1
LOTUS                     47
LUCID                      4
LUXGEN                     4
LX                         1
LYKAN                      1
LYNK & CO                 66
MAC                        1
MACLAREN                   2
MAEXTRO                    9
MAHINDRA                  42
MAN                        1
MANN                       1
MASERATI                 700
MAXUS                    520
MAYBACH                    5
MAZDA                   9352
MCLAREN                   78
MERCEDES                   1
MERCEDES BENZ          34015
MERCEDES-BENZ           1508
MERCURY                  191
MG                      7394
MHERO                      1
MINI                    2793
MINI COUPE                 1
MITSUBISHI             50484
MOCK                       1
MONTESA                    1
MORGAN                     6
MOTO GUZZI                 6
MV                         1
MV AGUSTA                  5
NETA                       2
NIO                       24
NISSAN                209435
NISSEN                     1
OCC                        1
OMODA                      3
OPEL                     223
PADAR                      1
PAGANI                     3
PEMBLETON                  1
PEUGEOT                 2704
PIAGGIO                   13
POL                        1
POLARIS                  137
POLESTAR                  83
PONTIAC                   10
PONTICA                    1
PORSCHE                 4384
POWER                      1
POWEREAGLE                14
PREVOST                    1
PROTON                     4
PUYUAN                     1
QINGLING                   4
RABDAN                   216
RAM                     2172
RANGE  ROVER               1
RANGE ROVER                3
RENAULT                 5375
RIDDARA                   15
RIVIAN                    25
ROCKY                      1
ROLLS ROYCE             1155
ROX                     2709
ROYAL ALLOY                1
ROYAL ENFIELD             58
SAAB                      14
SAIC                       2
SAIMO                      1
SAMSUNG                    1
SANDSTORM                  3
SANIYA                     1
SANY                       1
SANYA                    175
SANYOU                     1
SATURN                     3
SCANIA                     2
SCION                      3
SCORPA                     1
SEAT                      65
SERES                     47
SHANG JAN                  1
SHARAMAX                   3
SHARMAX                  134
SHARMAX ENDURO 2           1
SHERCO                     5
SILNGSHOT                  1
SINOTRUK                   1
SKODA                    843
SKYWELL                   10
SLING SHOT                 1
SLINGSHOT                  4
SMART                     85
SOUEAST                  115
SOUO                       1
SPYDER                     1
SSANGYONG                 22
STD                        1
SUBARU                   702
SUZUKI                 12043
SWIFT                      1
SWM                        1
SYM                       18
T7                         1
TAM                        2
TANK                     465
TATA                      75
TESLA                  12914
TESLA2130144264            1
TGB                        5
TOYOTA                239897
TOYOTA2100875058           1
TRALER                     1
TRD                        1
TRIUMPH                   34
TRUMPCHI                   3
TVS                      184
TYANMA                     1
UAZ                       13
UNICORN                    2
UNKNOWN                    1
VANDER                     1
VANDERHALL                13
VESPA                    235
VGV                        3
VICTORIA                   7
VICTORY                  584
VINFAST                    3
VOLG                       1
VOLKSWAGEN             10957
VOLTAMP                    7
VOLVO                   1028
VOYAH                     95
WIESMANN                   3
WULING                     5
XAOMI                     84
XCMG                       1
XIAOMI                    21
XPENG                     57
YADEA                      2
YAHAMA                     2
YAMAH                      1
YAMAHA                   351
YBR 125                    1
ZAMIYAD                    1
ZEEKR                    233
ZENIN                      1
ZERO                       1
ZHENGZHOU                  3
ZNA                       90
ZNIN                       1
ZONGSHEN                   7
ZONSEN                     5
ZONTES                     1
ZOTYE                     11
ZX AUTO                    1
ZXAUTO                     5
Name: count, dtype: int64